### ISSUE TITLE
Test the workshop on Windows and macOS

### ISSUE THREAD

**Issue by skade** [ferrous-systems/embedded-trainings#2]
The workshop should be set up and tested on Windows and macOS.

Preferably, installation instructions can be written along the way.

**Comment by Mirabellensaft** [comment]
I used this for installing the arm-eabi part on macOS:
https://github.com/eblot/homebrew-armeabi 

other then that, I followed the instructions in the installation guide and everything worked fine.

**Comment by skade** [comment]
:+1:
